### ISSUE TITLE
Will you accept pull requests?

### ISSUE THREAD

**Issue by ksbhaskar** [orbitalquark/lua-yottadb#1]
@orbitalquark Thank you for lua-yottadb. Will you consider pull requests for this repository from YottaDB developers? Thanks again.

Regards
Bhaskar (yes, it's my last name, but that's what I'm called)

**Comment by orbitalquark** [comment]
Yes, of course :)

**Comment by ksbhaskar** [comment]
Thank you. We'll do that. Also, we'll add a chapter on the Lua wrapper in the [YottaDB Multi-Language Programmers Guide](https://docs.yottadb.com/MultiLangProgGuide/). The [node.js chapter](https://docs.yottadb.com/MultiLangProgGuide/nodeprogram.html#) documents a wrapper written by a member of the YottaDB community. I understand that the University of Antwerp library sponsored your work, but to give you credit, please let me know the name by which you would like to be credited (and just “Mitchell” is fine is that's how you would like to be credited).

**Comment by orbitalquark** [comment]
Yes, just my first name is fine.
