### ISSUE TITLE
make test fails with lua5.4

### ISSUE THREAD

**Issue by jsikri94** [orbitalquark/lua-yottadb#11]
```
...
51/52 tests passed (0 skipped)
make: *** [Makefile:27: test] Error 1
```

Since `lock.sh` and `lock.lua` use lua5.3, one test fails when lua5.4 is used.

Is it possible to automatically get the current Lua version and use that in the test (and Makefile)? Or do the files(including Makefile) need to be manually updated?

**Comment by orbitalquark** [comment]
https://github.com/orbitalquark/lua-yottadb/commit/e581d9cab87bcd89c5f3f7d78746fb2df5297200 uses a version-agnostic `lua` executable.

**Comment by jsikri94** [comment]
Just tested it and it works as expected. Thank you.
