### ISSUE TITLE
What is a key object?

### ISSUE THREAD

**Issue by ksbhaskar** [orbitalquark/lua-yottadb#2]
Let me confess at the outset that I am yet to write a line of Lua code, although I am sure I will write my first line, and my second line, etc. before too long.

In reviewing the lua-yottadb documentation, I notice that a `key` is only used by the `key()` and `lock()` functions and a `key` is an object. The other functions have `(varname, subsarray)` parameters, which I am familiar with, as an M programmer. I am also familiar with objects, as a former Smalltalk-80 programmer.

What is a `key` (at least in this context) and how does it differ from `(varname, subsarray)`. Why does `lock()` use keys and why do the other functions use `(varname, subsarray)`? Any explanation or pointers to existing references are appreciated. Thank you very much in advance.

**Comment by orbitalquark** [comment]
The Lua-YottaDB API allows developers to pick which style they prefer: function style or object style. That's all there really is to it.

Function style uses `yottadb.func(varname, subsarray)` while object style uses `key:func()` where a `key` is created using `yottadb.key('varname')('subscript')`.

`yottadb.lock()` is special. It can accept a list of `key` objects or `{varname, subsarray}` tables.

I hope that helps.

**Comment by ksbhaskar** [comment]
@orbitalquark Thank you very much for the explanation.
