### ISSUE TITLE
Using a newer Lua version

### ISSUE THREAD

**Issue by ksbhaskar** [orbitalquark/lua-yottadb#3]
On my Arch Linux laptop:

```
$ rm _yottadb.so 
$ make
gcc -g -std=c99 -I/usr/local/lib/yottadb/r135_20220512-1 -I/usr/include/lua5.3 -Wno-discarded-qualifiers -shared -fPIC -o _yottadb.so _yottadb.c -L/usr/local/lib/yottadb/r135_20220512-1 -lyottadb 
_yottadb.c: In function ‘lock’:
_yottadb.c:498:75: warning: passing argument 2 of ‘ydb_call_variadic_plist_func’ makes pointer from integer without a cast [-Wint-conversion]
  498 |   int status = ydb_call_variadic_plist_func((ydb_vplist_func)&ydb_lock_s, (uintptr_t)args);
      |                                                                           ^~~~~~~~~~~~~~~
      |                                                                           |
      |                                                                           long unsigned int
In file included from _yottadb.c:7:
/usr/local/lib/yottadb/r135_20220512-1/libyottadb.h:348:75: note: expected ‘gparam_list *’ {aka ‘struct gparam_list_struct *’} but argument is of type ‘long unsigned int’
  348 | int     ydb_call_variadic_plist_func(ydb_vplist_func cgfunc, gparam_list *cvplist); /* Used by API wrappers for other languages to
      |                                                              ~~~~~~~~~~~~~^~~~~~~
$ ls _yottadb.so 
_yottadb.so
$ lua
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> local _yottadb = require('_yottadb')
version mismatch: app. needs 503.0, Lua core provides 504.0
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
```

Suggestions on how to fix it appreciated. Thank you.

**Comment by orbitalquark** [comment]
As mentioned in the README:

    If your Lua headers are elsewhere, you can either modify *Makefile* or pass `CFLAGS=-I/path/to/your/lua` to `make`.

The easiest option would be to modify *Makefile* to change lua5.3 to lua5.4, assuming your Lua headers are in */usr/include/lua5.4*.

**Comment by ksbhaskar** [comment]
Thanks @orbitalquark. Yes, that works. We sent out an announcement to our users yesterday that said, in part

>YottaDB now has a native API for the Lua programming language (https://www.lua.org/). The wrapper (https://github.com/orbitalquark/lua-yottadb) was created by Mitchell (https://github.com/orbitalquark) and sponsored by the University of Antwerp Library (https://www.uantwerpen.be/library/). We would like to thank Mitchell and the University of Antwerp Library for this important contribution.
>
> - Our Get Started page (https://yottadb.com/product/get-started/) gets you going immediately.
> - The Acculturation Guide includes access from Lua (https://docs.yottadb.com/AcculturationGuide/acculturation.html#access-from-lua).
> - The complete API is documented in the Lua section of the Multi-Language Programmers Guide (https://docs.yottadb.com/MultiLangProgGuide/luaprogram.html).

Another interesting part from that announcement is

> We also welcome Ram Sailopal back to the YottaDB blog (https://yottadb.com/blog/) with his second guest post, Comparing YottaDB Web Framework Performance (https://yottadb.com/comparing-yottadb-web-framework-performance/).

The interesting part is that the Lua framework is the fastest of those tested. So thank you very much for the Lua wrapper.

Are there good places where Lua developers hang out and where we can let them know about YottaDB support for Lua? You can also e-mail me directly at bhaskar at yottadb.com if you prefer.

**Comment by orbitalquark** [comment]
The Lua mailing list would be the place to announce such things: https://www.lua.org/lua-l.html

Thanks for letting me know about your announcement. I'm glad the bindings are working for you :)

**Comment by orbitalquark** [comment]
The Lua mailing list would be the place to announce such things: https://www.lua.org/lua-l.html

Thanks for letting me know about your announcement. I'm glad the bindings are working for you :)
