### ISSUE TITLE
Test only runs from lua-yottadb dir.

### ISSUE THREAD

**Issue by jsikri94** [orbitalquark/lua-yottadb#4]
Trying to run the `test.lua` file from the `tests` directory:
```
ydbuser@ydbdev:~/lua-yottadb/tests$ lua test.lua 
lua: test.lua:3: module '_yottadb' not found:
	no field package.preload['_yottadb']
	no file '/usr/local/share/lua/5.3/_yottadb.lua'
	no file '/usr/local/share/lua/5.3/_yottadb/init.lua'
	no file '/usr/local/lib/lua/5.3/_yottadb.lua'
	no file '/usr/local/lib/lua/5.3/_yottadb/init.lua'
	no file '/usr/share/lua/5.3/_yottadb.lua'
	no file '/usr/share/lua/5.3/_yottadb/init.lua'
	no file './_yottadb.lua'
	no file './_yottadb/init.lua'
	no file '/usr/local/lib/lua/5.3/_yottadb.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/_yottadb.so'
	no file '/usr/lib/lua/5.3/_yottadb.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './_yottadb.so'
stack traceback:
	[C]: in function 'require'
	test.lua:3: in main chunk
	[C]: in ?
ydbuser@ydbdev:~/lua-yottadb/tests$
```
Most of the paths above, being checked for the presence of .so and .lua files, don't exist.
For example;
```
ydbuser@ydbdev:~/lua-yottadb/tests$ ls -l /usr/local/lib/lua/5.3/
ls: cannot access '/usr/local/lib/lua/5.3/': No such file or directory
```

> Copy the newly built _yottadb.so and yottadb.lua files to somewhere in your Lua path.

I require some help in accomplishing the above statement, as I am not able to find the Lua path.
Thank you.

**Comment by orbitalquark** [comment]
*test.lua* was not designed to be run from the *tests/* directory, but rather using the *Makefile* rule `test`. Try running `make test`. That's the easiest way. Otherwise you'll have to put the requested files in one of those directories that Lua is searching for, or you'll have to use the `LUA_PATH` environment variable (see https://www.lua.org/manual/5.4/manual.html#pdf-LUA_PATH).

**Comment by jsikri94** [comment]
Ah, okay.

I tried `make test` and it worked. Thank you.
