### ISSUE TITLE
get_error_code() examples

### ISSUE THREAD

**Issue by jsikri94** [orbitalquark/lua-yottadb#5]
What type of string does `get_error_code()` expect as an input?
Could you provide a few examples?
Thank you.

**Comment by orbitalquark** [comment]
It expects an error string generated by a call to one of the Lua-YottaDB functions, which happen to be prefixed with 'YDB Error: ' (see https://github.com/orbitalquark/lua-yottadb/blob/977b8e7719b5c8360073f4fb4421d274e08a21cb/_yottadb.c#L47)

For example:

  ydb = require('yottadb')
  ydb.get('^foo')
  ./yottadb.lua:126: YDB Error: -150374122: %YDB-E-ZGBLDIRACC, Cannot access global directory !AD!AD!AD.
  stack traceback:
    [C]: in function 'error'
    ./yottadb.lua:126: in function 'yottadb.get'
    (...tail calls...)
    [C]: in ?

The error string is "YDB Error: -150374122: %YDB-E-ZGBLDIRACC, Cannot access global directory !AD!AD!AD."

**Comment by jsikri94** [comment]
Got it. Thank you.
