### ISSUE TITLE
Update ydb_dist variable in Makefile

### ISSUE THREAD

**Issue by jsikri94** [orbitalquark/lua-yottadb#9]
Currently `ydb_dist` has the value `$(shell pwd)/YDB/install` in the Makefile. It should be populated by using pkgconfig in the following manner:

```
ydb_dist=$(pkg-config --variable=prefix yottadb)
```

**Comment by orbitalquark** [comment]
Addressed via https://github.com/orbitalquark/lua-yottadb/commit/afcf9cd02f3f623fbe631aa29574ae778759731c

**Comment by ksbhaskar** [comment]
Thanks @orbitalquark
